--- 
title: "Shows App Project"
author: "TechAcademy e.V."
date: "Winter Term 2022/2023"
site: bookdown::bookdown_site
---
--- 
title: "Shows App Project"
author: "TechAcademy e.V."
date: "Winter Term 2022/2023"
site: bookdown::bookdown_site
---

# Introduction
Welcome to the Web Development program for the winter term of 2022/23! We are very excited to have you here. In these first paragraphs we want to briefly introduce our program and give you an overview of what to expect in the following months as well as lay out the content of this guideline. We will help and guide you along the way to the best of our abilities and hope we can share some of that fascination that got us into programming with you!  

Over the next months, there will be a total of four Coding Meetups, spaced out evenly where you will have the ability to meet your peers, work together on our application and ask questions to your mentors. In preparation we partnered up with Udemy and thus you have free access to the ultimate Web Development Bootcamp course. Everything you will learn there, you can later use within your own project and solidify your knowledge. We will go over the course and establish a timeframe on how far you should have progressed before each meetup later on. Feel free to sprint ahead on your own though, we are only laying out the minimal requirements here.  


In your project, you can work in groups of up to four team members. You can choose your teammates independently and we will not interfere with your arrangements. It is however beneficial, that all group members have approximately the same level of knowledge. We explicitly encourage you to collaborate with students from different university faculties. This not only allows you to get to know people from other faculties, but may also give you a whole new perspective on the project and tasks. When submitting your project please note: for a certificate, each person must submit the project individually. However, hand-ins may be similar within your group. You can get more information at our first Coding Meetup on **November 9, 2022.**
  
So.. what is our project? For this term, we have decided to let you create a show app. Just like your favourite streaming platforms Netflix, Disney+ or Amazon Prime. Most of us use these streaming platforms every day and therefore we all know how to use them. But how does the data get to the website? How does it update with every new search and how can one make look that all appealing to an audience? These are all questions that we will tackle in this semester.

This project guide was developed and written by the Web Development team at TechAcademy: [Sebastian Hönig](https://www.linkedin.com/in/sebastian-hönig/), [Burak Onat](https://www.linkedin.com/in/tburakonat/). Special thanks also to Ben Lucht, Feron Basoeki, Tom Schwitzkowski and Tilo Flasche who were responsible for the Web Development course in the past.



<!--chapter:end:index.Rmd-->


# What's web development?

Placeholder


## How to use this section
## HTML
### Tags {-}  
### Structure {-} 
## CSS
### Syntax {-}  
### Common properties {-}    
### Box Model {-}  
### Style.css {-}  
## JavaScript
### Code samples {-}  
### The DOM {-}  
### Script.js {-}  

<!--chapter:end:02-Introduction.Rmd-->

---
output:
  pdf_document: default
  html_document: default
---
# Tools

## IDE

Now that you know the basics of Web Development you are ready to go and write some code!

But there is still a question left to answer: Where do programmers write their code?

As we have already pointed out, you could start programming in the default text editor of your operating system, however take our word when we say: Don't. You will regret it. Most developers use an Integrated Development Environment (IDE) to write code because it comes with a lot of handy features that help developers code faster and cleaner. Once you get used to an IDE, you will never look back. Let's look at some reasons they're so handy.  

**1. Graphical User Interface**  
The GUI of an IDE has been designed in a way that allows you to see your project directory, editor and terminal all at once. This makes it very easy to navigate between the different html, css and javascript files.

**2. Autocomplete**  
If the IDE knows your programming language it can anticipate what you are going to type next and thus allow for faster development.

**3. Syntax Highlighting**  
An IDE that knows the syntax of your programming language can provide visual cues. Keywords, words that have special meaning like if, for or while in JavaScript, are highlighted with different colors. 

**4. Debugging**  
No one can avoid to write code without errors. IDEs provide hints while coding to prevent errors before compilation and help you with debugging afterwards.

Some popular IDEs for Web Development are Visual Studio Code, Vim and Sublime Text 3. In the Udemy course your instructor will use Visual Studio Code. Feel free to check it out [here](https://code.visualstudio.com/).

For this course and your project, you will use the online code editor [CodeSandbox](https://codesandbox.io/). We will set up the environment together in the first Meetup. This IDE is based on the same platform as Visual Studio Code, but offers some additional functionalities. The user interface has been designed in a way that allows you to see your file directory, editor, and your executed program all at once. CodeSandbox allows you to create teams that can not only access the same files but also make it possible to have live coding session together. To sign up you only need a free Github account, which you can create in a matter of seconds.

## Udemy

For this course you will be working with the [The Web Development Bootcamp 2022](https://www.udemy.com/course/the-web-developer-bootcamp/) on Udemy.
  
This course is filled with a ton of content. For our project we are only focusing on the front-end so you can naturally ignore (for now) the later half of the course, which exclusively deals with the back-end. We encourage you to do all the exercises you will encounter in between. You are going to learn a lot by doing the exercises and programming on your project will become far simpler.

The following sections should leave you with enough knowledge to complete your project:

| Section Name                              | Duration (h) |
|-------------------------------------------|--------------|
| 1. Course Orientation                     | 0.5 |
| 2. An Introduction to Web Development     | 0.75 |
| 6. CSS: The Very Basics                   | 1 |
| 7. CSS: The World of CSS Selectors        | 1.25 |
| 8. The CSS Box Model                      | 1 |
| 10. Responsive CSS & Flexbox              | 1.25 |
| 14. JavaScript Basics!                    | 1 |
| 15. JavaScript String and More            | 0.75 |
| 16. JavaScript Decision Making            | 1.25 |
| 17. JavaScript Arrays                     | 1 |
| 18. JavaScript Object Literals            | 0.5 |
| 19. JavaScript Repeating Stuff With Loops | 1.5 |
| 20. NEW: Introducing Functions            | 0.5 |
| 21. Leveling Up Our Functions             | 1 |
| 22. Callbacks & Array Methods             | 1.5 |
| 24. Introducing The World Of The DOM      | 1.75 |
| 25. The Missing Piece: DOM Events         | 1.75 |

## API

For this semester project you will also need to learn about APIs. But what exactly is an API? An API (Application Programming Interface) allows different devices to connect to each other and send, update and request data from one to the other. You can think of it as a waiter in a restaurant. The waiter takes and understands your order, delivers it to the kitchen and comes back with the requested order. APIs function in a similar way.  

### How do we get the data? {-}
Every API is unique but if you understand how to obtain output from one API you will know how to get data from all.
For the most part, APIs are accessed through URLs, and the specifics of how to query these URLs change based on the specific service you are using. For example, the [TVMAZE API](https://www.tvmaze.com/api), that we will be using in our project, has several types of data that you can request. To search through all the shows in their database by the show's name you can use the following URL.
```
https://api.tvmaze.com/search/shows?q=girls
```
You can see that we access the URL and append our searchterm to it. The server will understand what we want and will return a response with all necessary information. To use some APIs you might need to create an account to obtain an API key. By doing this the server will know who requested an information and will block your account if you send too many API requests. To use the API for your project you don't need an account.

Congrats, you have made your first API request!  
  
So how do we actually get the data from an API into our code?  

In JavaScript we use the [Fetch API](https://developer.mozilla.org/de/docs/Web/API/Fetch_API) to make our API call.  You will learn more about how to use it in section [28](https://www.udemy.com/course/the-web-developer-bootcamp/learn/lecture/22051352#overview) of the Udemy course which will also go over [JSON][JSON], the text format of the weather data.  
To provide you with a template for later on and as a reminder, this is one way of how to deal with fetch:
```{javascript}
async function exampleAPICall() {
  try {
    const response = await fetch(
      "https://api.tvmaze.com/search/shows?q=girls"
    );
    const data = await response.json();
    /* your code here to work with the data */
  } catch (error) {
    console.log(error);
  }
}
```

<!--chapter:end:03-Tools.Rmd-->


# Project

Placeholder


## Project introduction
## Minimal Requirements
### 1. Search Bar and Button {-}
### 2. API Call {-}
### 3. Rendering the Shows {-}
### 4. Modal with more information {-}
## More Ideas
## Curriculum
### 09.11.2022 - Web-Dev Coding Introduction {-}
#### Udemy Course {-}
### 23.11.2022 - 1. Coding Meetup {-}
#### Udemy Course {-}
#### Action {-}
### 14.12.2022 - 2. Coding Meetup {-}
#### Udemy Course {-}
#### Action {-}
### 11.01.2023 - 3. Coding Meetup {-}
#### Udemy Course {-}
#### Action {-}
### 01.02.2023 - 4. Coding Meetup {-}
#### Udemy Course {-}
#### Action {-}

<!--chapter:end:04-Project.Rmd-->


# Additional Resources

Placeholder


## Git and GitHub
## JSON
## Font Awesome

<!--chapter:end:05-Additional-Resources.Rmd-->

